import ctypes
import hashlib
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import torch


THIS_DIR = Path(__file__).resolve().parent
DEFAULT_KERNEL_CPP = THIS_DIR / "fa_performance_kernel.cpp"
DEFAULT_BUILD_ROOT = THIS_DIR / ".jit"

CV_FIFO_SIZE = 8
CUBE_S1 = 128
TILE_S1 = 256
CV_COMM_SLOT_BYTES = 512


def torch_to_ctypes(t: torch.Tensor) -> ctypes.c_void_p:
    return ctypes.c_void_p(t.data_ptr())


@dataclass(frozen=True)
class TfaCase:
    head_size: int
    s0: int
    s1: int
    cube_s0: int
    cube_s1: int = CUBE_S1
    tile_s1: int = TILE_S1
    qk_preload: int = 4
    causal: bool = False

    def validate(self) -> "TfaCase":
        fields = {
            "head_size": self.head_size,
            "s0": self.s0,
            "s1": self.s1,
            "cube_s0": self.cube_s0,
            "cube_s1": self.cube_s1,
            "tile_s1": self.tile_s1,
            "qk_preload": self.qk_preload,
        }
        for name, value in fields.items():
            if value <= 0:
                raise ValueError(f"{name} must be > 0, got {value}")
        if self.s0 % self.cube_s0 != 0:
            raise ValueError(f"s0 ({self.s0}) must be divisible by cube_s0 ({self.cube_s0})")
        if self.s1 % self.cube_s1 != 0:
            raise ValueError(f"s1 ({self.s1}) must be divisible by cube_s1 ({self.cube_s1})")
        if self.tile_s1 % self.cube_s1 != 0:
            raise ValueError(f"tile_s1 ({self.tile_s1}) must be divisible by cube_s1 ({self.cube_s1})")
        if self.s1 % self.tile_s1 != 0:
            raise ValueError(f"s1 ({self.s1}) must be divisible by tile_s1 ({self.tile_s1})")
        return self

    @property
    def block_rows(self) -> int:
        return self.s0 // self.cube_s0

    @property
    def num_tiles(self) -> int:
        return self.s1 // self.tile_s1

    @property
    def name(self) -> str:
        mask = "causal" if self.causal else "dense"
        return f"H{self.head_size}_S0{self.s0}_S1{self.s1}_C0{self.cube_s0}_T{self.tile_s1}_P{self.qk_preload}_{mask}"


def _pick_cube_s0(s0: int, cube_s0: int | None) -> int:
    if cube_s0 is not None:
        return cube_s0
    return 128 if s0 >= 128 and s0 % 128 == 0 else s0


def _ascend_home() -> Path:
    for key in ("ASCEND_HOME_PATH", "ASCEND_TOOLKIT_HOME", "ASCEND_HOME"):
        value = os.environ.get(key)
        if value:
            return Path(value)

    for entry in os.environ.get("LD_LIBRARY_PATH", "").split(":"):
        path = Path(entry)
        if path.name == "lib64" and path.parent.name.startswith("cann-"):
            return path.parent

    raise RuntimeError("ASCEND_HOME_PATH or ASCEND_TOOLKIT_HOME must be set")


def _pto_root() -> Path:
    #value = os.environ.get("PTO_LIB_PATH")
    value = '/home/fskogh/famy/3p/pto-isa/'
    if not value:
        raise RuntimeError("PTO_LIB_PATH must point to the PTO install/source prefix")
    return Path(value)


def _compiler() -> str:
    compiler = os.environ.get("CXX") or "bisheng"
    if shutil.which(compiler) is None:
        raise RuntimeError(f"Compiler '{compiler}' was not found in PATH")
    return compiler


def _cce_arch_flag() -> str:
    arch = os.environ.get("CCE_AICORE_ARCH") or os.environ.get("NPU_ARCH")
    if arch:
        arch = arch.strip()
        if arch.startswith("dav-c"):
            return f"--cce-aicore-arch={arch}"
        return f"--npu-arch={arch}"

    soc = os.environ.get("SOC_VERSION", "")
    if "Ascend910_9599" in soc:
        return "--cce-aicore-arch=dav-c310"
    return "--cce-aicore-arch=dav-c220"


def _case_key(case: TfaCase, kernel_cpp: Path) -> str:
    payload = f"{case!r}:{kernel_cpp.resolve()}".encode() + kernel_cpp.read_bytes()
    return hashlib.sha1(payload).hexdigest()[:12]


def _write_if_changed(path: Path, text: str) -> None:
    if path.exists() and path.read_text() == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _render_kernel_source(case: TfaCase, kernel_cpp: Path) -> str:
    causal = "true" if case.causal else "false"
    kernel_include = kernel_cpp.resolve().as_posix()
    template_args = (
        f"{case.s0}, {case.head_size}, {case.s1}, {case.cube_s0}, {case.cube_s1}, "
        f"{case.tile_s1}, {case.qk_preload}, kFaCvFifoSize, false, {causal}, kFaCvFifoConsSyncPeriod"
    )
    return f"""// Auto-generated by flash_atten/jit_util.py.
#include "{kernel_include}"

template void LaunchTFA<{template_args}>(
    uint16_t *ffts, aclFloat16 *q, aclFloat16 *k, aclFloat16 *v, aclFloat16 *p_tile_fifo,
    float *exp_max_ififo, float *global_sum_out, float *exp_max_out, float *o_out, float *o_parts_out,
    float *qk_tile_fifo, float *pv_tile_fifo, uint8_t *profile_data, aclrtStream stream, uint8_t *cv_comm_buf);

template void LaunchTFA<{template_args}>(
    uint16_t *ffts, aclFloat16 *q, aclFloat16 *k, aclFloat16 *v, aclFloat16 *p_tile_fifo,
    float *exp_max_ififo, float *global_sum_out, float *exp_max_out, float *o_out, float *o_parts_out,
    float *qk_tile_fifo, float *pv_tile_fifo, aclrtStream stream, uint8_t *cv_comm_buf);
"""


def _render_wrapper(case: TfaCase) -> str:
    return f"""#include <cstdint>

#include "fa_performance_kernel.h"

#include "runtime/rt.h"

extern "C" int call_kernel(void *stream, void *q, void *k, void *v, void *p_tile_fifo, void *exp_max_ififo,
                           void *global_sum_out, void *exp_max_out, void *o_out, void *o_parts_out,
                           void *qk_tile_fifo, void *pv_tile_fifo, void *cv_comm_buf)
{{
    uint64_t ffts = 0;
    uint32_t ffts_len = 0;
    rtGetC2cCtrlAddr(&ffts, &ffts_len);

    LaunchTFA<{case.s0}, {case.head_size}, {case.s1}, {case.cube_s0}, {case.cube_s1}, {case.tile_s1},
              {case.qk_preload}, kFaCvFifoSize, false, {"true" if case.causal else "false"},
              kFaCvFifoConsSyncPeriod>(
        reinterpret_cast<uint16_t *>(ffts), reinterpret_cast<aclFloat16 *>(q), reinterpret_cast<aclFloat16 *>(k),
        reinterpret_cast<aclFloat16 *>(v), reinterpret_cast<aclFloat16 *>(p_tile_fifo),
        reinterpret_cast<float *>(exp_max_ififo), reinterpret_cast<float *>(global_sum_out),
        reinterpret_cast<float *>(exp_max_out), reinterpret_cast<float *>(o_out),
        reinterpret_cast<float *>(o_parts_out), reinterpret_cast<float *>(qk_tile_fifo),
        reinterpret_cast<float *>(pv_tile_fifo), reinterpret_cast<aclrtStream>(stream),
        reinterpret_cast<uint8_t *>(cv_comm_buf));
    return 0;
}}
"""


def _common_include_flags(build_dir: Path) -> list[str]:
    ascend_home = _ascend_home()
    ascend_driver = Path(os.environ.get("ASCEND_DRIVER_PATH", "/usr/local/Ascend/driver"))
    pto_root = _pto_root()

    return [
        f"-I{pto_root / 'include'}",
        f"-I{THIS_DIR}",
        f"-I{build_dir}",
        f"-I{ascend_home / 'include'}",
        f"-I{ascend_home / 'pkg_inc'}",
        f"-I{ascend_home / 'pkg_inc' / 'runtime'}",
        f"-I{ascend_home / 'pkg_inc' / 'profiling'}",
        f"-I{ascend_driver / 'kernel' / 'inc'}",
        f"-I{ascend_home / 'include' / 'experiment' / 'runtime'}",
        f"-I{ascend_home / 'include' / 'experiment' / 'msprof'}",
    ]


def _kernel_compile_command(kernel_cpp: Path, kernel_lib_path: Path, build_dir: Path) -> list[str]:
    flags = [
        "-fPIC",
        "-shared",
        "-D_FORTIFY_SOURCE=2",
        "-O2",
        "-std=c++17",
        "-Wno-macro-redefined",
        "-Wno-ignored-attributes",
        "-fstack-protector-strong",
        "-xcce",
        "-Xhost-start",
        "-Xhost-end",
        "-mllvm",
        "-cce-aicore-stack-size=0x8000",
        "-mllvm",
        "-cce-aicore-function-stack-size=0x8000",
        "-mllvm",
        "-cce-aicore-record-overflow=true",
        "-mllvm",
        "-cce-aicore-addr-transform",
        "-mllvm",
        "-cce-aicore-dcci-insert-for-scalar=false",
        _cce_arch_flag(),
        *_common_include_flags(build_dir),
    ]

    return [_compiler(), *flags, str(kernel_cpp), "-o", str(kernel_lib_path), "--cce-fatobj-link"]


def _wrapper_compile_command(wrapper_cpp: Path, kernel_lib_path: Path, lib_path: Path, build_dir: Path) -> list[str]:
    ascend_home = _ascend_home()

    flags = [
        "-fPIC",
        "-shared",
        "-D_FORTIFY_SOURCE=2",
        "-O2",
        "-std=c++17",
        "-Wno-macro-redefined",
        "-Wno-ignored-attributes",
        "-fstack-protector-strong",
        "-xc++",
        "-include",
        "stdint.h",
        "-include",
        "stddef.h",
        *_common_include_flags(build_dir),
    ]

    link_flags = [
        "-x",
        "none",
        str(kernel_lib_path),
        f"-Wl,-rpath,{build_dir}",
        f"-L{ascend_home / 'lib64'}",
        "-lruntime",
        "-lstdc++",
        "-lascendcl",
        "-lm",
        "-ltiling_api",
        "-lplatform",
        "-lc_sec",
        "-ldl",
        "-lnnopbase",
        "-lpthread",
    ]

    return [_compiler(), *flags, str(wrapper_cpp), "-o", str(lib_path), *link_flags]


def compile_flash(
    kernel_cpp: str | os.PathLike[str] = DEFAULT_KERNEL_CPP,
    *,
    head_size: int = 128,
    s0: int = 128,
    s1: int = 1024,
    cube_s0: int | None = None,
    tile_s1: int = TILE_S1,
    qk_preload: int = 4,
    causal: bool = False,
    build_root: str | os.PathLike[str] = DEFAULT_BUILD_ROOT,
    force: bool = False,
    verbose: bool = False,
    timeout: int = 300,
) -> tuple[Path, TfaCase]:
    """
    Build fa_performance_kernel.cpp for one concrete TFA shape.

    The generated shared object exports:
        int call_kernel(void *stream, void *q, void *k, void *v, ...workspace...)
    """
    kernel_cpp = Path(kernel_cpp)
    if not kernel_cpp.is_absolute():
        kernel_cpp = (Path.cwd() / kernel_cpp).resolve()

    case = TfaCase(
        head_size=head_size,
        s0=s0,
        s1=s1,
        cube_s0=_pick_cube_s0(s0, cube_s0),
        tile_s1=tile_s1,
        qk_preload=qk_preload,
        causal=causal,
    ).validate()

    build_dir = Path(build_root) / _case_key(case, kernel_cpp)
    build_dir.mkdir(parents=True, exist_ok=True)
    jit_kernel_cpp = build_dir / "jit_kernel.cpp"
    wrapper_cpp = build_dir / "jit_wrapper.cpp"
    kernel_lib_path = build_dir / f"libflash_kernel_{case.name}.so"
    lib_path = build_dir / f"flash_jit_{case.name}.so"

    _write_if_changed(jit_kernel_cpp, _render_kernel_source(case, kernel_cpp))
    _write_if_changed(wrapper_cpp, _render_wrapper(case))

    if kernel_lib_path.exists() and lib_path.exists() and not force:
        return lib_path, case

    commands = [
        _kernel_compile_command(jit_kernel_cpp, kernel_lib_path, build_dir),
        _wrapper_compile_command(wrapper_cpp, kernel_lib_path, lib_path, build_dir),
    ]
    for cmd in commands:
        if verbose:
            print("compile command:\n" + " ".join(cmd))
        try:
            subprocess.run(cmd, check=True, timeout=timeout)
        except Exception as exc:
            raise RuntimeError(f"Compile failed for {case.name}: {exc}") from exc

    return lib_path, case


class FlashTfa:
    def __init__(self, lib_path: Path, case: TfaCase):
        self.case = case
        self.lib_path = Path(lib_path)
        for dep in self.lib_path.parent.glob("libflash_kernel_*.so"):
            ctypes.CDLL(str(dep), mode=ctypes.RTLD_GLOBAL)
        self.lib = ctypes.CDLL(str(self.lib_path), mode=ctypes.RTLD_GLOBAL)
        self.lib.call_kernel.argtypes = [ctypes.c_void_p] * 13
        self.lib.call_kernel.restype = ctypes.c_int
        self._ws: dict[str, torch.Tensor | tuple[str, TfaCase]] = {}

    def _alloc_workspace(self, device: torch.device) -> None:
        key = (str(device), self.case)
        if self._ws.get("_key") == key:
            return

        case = self.case
        qk_elems = case.block_rows * CV_FIFO_SIZE * case.cube_s0 * case.tile_s1
        pv_elems = case.block_rows * CV_FIFO_SIZE * case.cube_s0 * case.head_size
        exp_max_elems = case.block_rows * CV_FIFO_SIZE * case.cube_s0
        stats_elems = case.num_tiles * case.s0
        o_parts_elems = case.num_tiles * case.s0 * case.head_size
        cv_comm_bytes = case.block_rows * CV_COMM_SLOT_BYTES

        self._ws.clear()
        self._ws["_key"] = key
        self._ws["p_tile_fifo"] = torch.empty(qk_elems, device=device, dtype=torch.float16)
        self._ws["exp_max_ififo"] = torch.empty(exp_max_elems, device=device, dtype=torch.float32)
        self._ws["global_sum_out"] = torch.empty(stats_elems, device=device, dtype=torch.float32)
        self._ws["exp_max_out"] = torch.empty(stats_elems, device=device, dtype=torch.float32)
        self._ws["o_out"] = torch.empty((case.s0, case.head_size), device=device, dtype=torch.float32)
        self._ws["o_parts_out"] = torch.empty(o_parts_elems, device=device, dtype=torch.float32)
        self._ws["qk_tile_fifo"] = torch.empty(qk_elems, device=device, dtype=torch.float32)
        self._ws["pv_tile_fifo"] = torch.empty(pv_elems, device=device, dtype=torch.float32)
        self._ws["cv_comm_buf"] = torch.empty(cv_comm_bytes, device=device, dtype=torch.uint8)

    def __call__(
        self,
        q: torch.Tensor,
        k: torch.Tensor,
        v: torch.Tensor,
        stream_ptr: ctypes.c_void_p | int | None = None,
    ) -> torch.Tensor:
        case = self.case
        if q.shape != (case.s0, case.head_size):
            raise ValueError(f"q must have shape {(case.s0, case.head_size)}, got {tuple(q.shape)}")
        if k.shape != (case.s1, case.head_size):
            raise ValueError(f"k must have shape {(case.s1, case.head_size)}, got {tuple(k.shape)}")
        if v.shape != (case.s1, case.head_size):
            raise ValueError(f"v must have shape {(case.s1, case.head_size)}, got {tuple(v.shape)}")
        if q.dtype != torch.float16 or k.dtype != torch.float16 or v.dtype != torch.float16:
            raise TypeError("q, k, and v must be float16 tensors")
        if q.device != k.device or q.device != v.device:
            raise ValueError("q, k, and v must be on the same device")
        if not q.is_contiguous() or not k.is_contiguous() or not v.is_contiguous():
            raise ValueError("q, k, and v must be contiguous")

        self._alloc_workspace(q.device)
        if stream_ptr is None:
            stream_ptr = torch.npu.current_stream()._as_parameter_
        if not isinstance(stream_ptr, ctypes.c_void_p):
            stream_ptr = ctypes.c_void_p(int(stream_ptr))

        ws = self._ws
        ret = self.lib.call_kernel(
            stream_ptr,
            torch_to_ctypes(q),
            torch_to_ctypes(k),
            torch_to_ctypes(v),
            torch_to_ctypes(ws["p_tile_fifo"]),
            torch_to_ctypes(ws["exp_max_ififo"]),
            torch_to_ctypes(ws["global_sum_out"]),
            torch_to_ctypes(ws["exp_max_out"]),
            torch_to_ctypes(ws["o_out"]),
            torch_to_ctypes(ws["o_parts_out"]),
            torch_to_ctypes(ws["qk_tile_fifo"]),
            torch_to_ctypes(ws["pv_tile_fifo"]),
            torch_to_ctypes(ws["cv_comm_buf"]),
        )
        if ret != 0:
            raise RuntimeError(f"call_kernel failed with status {ret}")
        return ws["o_out"]


def jit_compile_flash(
    *,
    verbose: bool = False,
    clean_up: bool = False,
    kernel_cpp: str | os.PathLike[str] = DEFAULT_KERNEL_CPP,
    head_size: int = 128,
    s0: int = 128,
    s1: int = 1024,
    cube_s0: int | None = None,
    tile_s1: int = TILE_S1,
    qk_preload: int = 4,
    causal: bool = False,
    force: bool = False,
) -> FlashTfa:
    lib_path, case = compile_flash(
        kernel_cpp,
        head_size=head_size,
        s0=s0,
        s1=s1,
        cube_s0=cube_s0,
        tile_s1=tile_s1,
        qk_preload=qk_preload,
        causal=causal,
        force=force,
        verbose=verbose,
    )
    flash = FlashTfa(lib_path, case)
    if clean_up:
        try:
            os.remove(lib_path)
        except OSError:
            pass
    return flash
